### ISSUE TITLE
[iOS] Add Display layer view state sample

### ISSUE THREAD

**Issue by anttikajanus** [Esri/arcgis-runtime-samples-xamarin#118]
The sample displays the list of operational layers in the map. Each row in this list also has the view status corresponding to that layer. If you pan or zoom the map, the view status of some layers may change. 

The layer's view status could be 

- Active
- Not Visible
- Out of Scale
- Loading
- Error

Please see [iOS sample](https://developers.arcgis.com/ios/beta/swift/sample-code/display-layer-view-state.htm) as a reference.

**Comment by apurvag123** [comment]
merged
