### ISSUE TITLE
Missing Static Libraries in iOS examples.

### ISSUE THREAD

**Issue by estebanarmas** [Esri/arcgis-runtime-samples-xamarin#35]
Hi!.
I'm getting an error when i try to build and run any example of Xamarin iOS.(image attached).
I've checked the configuration and the package reference of the SDK, and everything looks normal, but still i'm getting this error.
BTW, i've been using Xamarin Studio in a Macbook Pro.
Thanks for your help!.
<img width="1413" alt="Missing Libraries in Xamarin Studio with ArcGIS SDK" src="https://cloud.githubusercontent.com/assets/11743605/14278746/93d882aa-fb29-11e5-943f-c8b0f1a371f7.png">

**Comment by anttikajanus** [comment]
Hi,
This is part of the known issue that we are now investigating and it also happens on Xamarin Forms iOS. It is related how Nuget is copying static libraries on restore and there seems to be some challenges with it. There are couple things that you can try:

Copy content from `packages\Esri.ArcGISRuntime.Xamarin.100.0.0.1287-beta\staticlib\Xamarin.iOS10` to `src\iOS\Xamarin.iOS\lib` folder

or 

- Uninstall nuget package
- Install nugget package
- rebuild the solution
- verify that `lib` folder is located at `src\iOS\Xamarin.iOS\lib`

NOTE 

In Visual Studio you need to initialise `Package Manager Console` by opening it from `Tools\NugetPackageManager\` before Nuget restore to ensure that the static libraries are copied correctly.

**Comment by anttikajanus** [comment]
This issue has been resolved in new Nuget drop in early adapter site.
