### ISSUE TITLE
Android error- "Project file was unloaded."

### ISSUE THREAD

**Issue by PoorvaJambhale** [Esri/arcgis-runtime-samples-xamarin#58]
When I try to open the solution for the Android in Visual Studio 2015, by clicking the (.sln) file as mentioned in the Readme, I see - "The Project file was unloaded" under the solution explorer. Not sure if there is an issue or if I am missing something.

**Comment by anttikajanus** [comment]
Hi,
Does other platforms work? I just pulled latest and opened the android one and didn't see any issues. Could you have a look if there is any other messages in Output window?

Which version of Visual Studio you are using? Which operation system version you have?

**Comment by PoorvaJambhale** [comment]
Hi,

I am using Visual Studio 2015 with Windows 8.

My earlier mentioned issue is now resolved. I reinstalled Xamarin and the project is now loaded in Visual studio. But I see below error in output window - **NuGet Package restore failed for project ArcGISRuntime.Xamarin.Samples.Android: Unable to find version '100.0.0.1278-beta' of package 'Esri.ArcGISRuntime.Xamarin'.** I see the same error in Xamarin Studio as well. I looked up and I found that - **Esri.ArcGISRuntime.Xamarin.100.0.0.1287-beta** is installed on my machine. Notice the 1278 Vs 1287? If this is the issue, how can I fix it?

Appreciate your help.
Thank you,
Poorva.

**Comment by mbranscomb** [comment]
@PoorvaJambhale This is unusual since there never was a 1278-beta.
Please can you try the following:
- Open packages.config in your project (should open as XML)
- Update the package Esri.ArcGISRuntime.Xamarin to version="100.0.0.1287-beta"
- Save and close the packages.config file
- Rich click the project in Solution Explorer
- Choose Manage Nuget Packages
- Uninstall/Install the nuget reference via the dialog?

**Comment by mbranscomb** [comment]
@PoorvaJambhale Alternatively re-forking the samples repo should fix this.

**Comment by PoorvaJambhale** [comment]
@mbranscomb Thank you! That issue was fixed. I am however seeing below error messages in output window when I build - 
**error CS0246: The type or namespace name 'Esri' could not be found: **
In files - ArcGISTiledLayerLocalTPK.cs, MapRotation.cs, SimpleMarkerSymbol.cs

I also see error message -** error CS0246: The type or namespace name 'MapView' could not be found**  in the same above 3 files.

**Comment by anttikajanus** [comment]
@PoorvaJambhale Please pull the latest. Sounds like your branch is old one. Also Make also sure that all references are found and there aren't any error marking in references list when you open it on the project level.

One thing that VS does time to time is that even if it says that references wasn't found it still works if you run it (not build, just run in debug or release modes).
