### ISSUE TITLE
DisplayDrawingStatus

### ISSUE THREAD

**Issue by cy-nwg** [Esri/arcgis-runtime-samples-xamarin#90]
Using this sample, the indicator runs and stops on the initial map load.  If I double click the map to zoom in, the draw status changes to InProgress but never back to Completed, so the indicator keeps running.

If I change the layer load to use the code below, it appears to work as expected.

FeatureLayer myFeatureLayer = new FeatureLayer(new Uri("http://sampleserver6.arcgisonline.com/arcgis/rest/services/DamageAssessment/FeatureServer/0"));
await myFeatureLayer.LoadAsync();

But, if the location display is started using Default pan mode, the drawing status cycles between InProgress and Completed, causing the indicator to show/hide.  I am simulating a single location and the map is not moving.  

Using an iOS simulator, have not tested on a real device but will try to do so.

**Comment by anttikajanus** [comment]
I think that what you are seeing here is related to the event and how it works. When you use `LocationDisplay` you most likely see an ping animation around the location symbol and when that animation is drawn, the status is drawing in the `MapView`. You can disable the animation using `myMapView.LocationDisplay.ShowPingAnimationSymbol = false;`.

**Comment by cy-nwg** [comment]
Disabling animation does in fact resolve it.  Thanks.
