### ISSUE TITLE
Change Basemap Question

### ISSUE THREAD

**Issue by cy-nwg** [Esri/arcgis-runtime-samples-xamarin#91]
The change basemap sample shows how to do this, but wondering the recommended approach when the view is zoomed to a location, and other feature layers are loaded.  Currently changing the map causes the map to zoom back out to the full scale.

Anything better than this?

- Save the view point
- Change the basemap 
- Load feature layers
- Reset the view point

**Comment by anttikajanus** [comment]
You should be able just to change `Map.Basemap = yourbasemap` and that should do the trick.

**Comment by anttikajanus** [comment]
Please reference https://github.com/Esri/arcgis-runtime-samples-xamarin/tree/master/src/iOS/Xamarin.iOS/Samples/Map/ChangeBasemap

**Comment by cy-nwg** [comment]
Missed that, thanks.
